### PR TITLE
Add build status notice to readme

### PR DESCRIPTION
**Pull request by jamesgk**

### CODE REVIEW

**Comment by jamesgk** [comment]
The mac build is taking >1 hour to start. Is this common?

**Comment by jamesgk** [comment]
Also, I suggest only building on PRs or pushes to master (not all pushes).

**Comment by anthrotype** [comment]
I think it's better to keep it on all branches. You can use `[skip ci]` anywhere in the commit message if you wish to skip the build:
https://docs.travis-ci.com/user/customizing-the-build#Skipping-a-build
https://www.appveyor.com/docs/how-to/filtering-commits/#skip-directive-in-commit-message

**Comment by anthrotype** [comment]
@jamesgk @behdad  I see https://ci.appveyor.com/project/googlei18n/compreffor can't be reached. It would be to also enable Appveyor CI for the upstream repository, like I have it on my fork https://ci.appveyor.com/project/anthrotype/compreffor

**Pull request merged**
