### PR TITLE
setup CI for running tests and bulding OSX, Linux and Windows wheels

### PR DESCRIPTION
**Pull request by anthrotype**
TL;DR ... read the commit log if you are interested

### CODE REVIEW

**Comment by anthrotype** [comment]
The tests pass:
https://travis-ci.org/anthrotype/compreffor/builds/152752639
https://ci.appveyor.com/project/anthrotype/compreffor/build/1.0.53

**Comment by anthrotype** [comment]
I just pushed some clean-ups and squashed a few commits.

I also bumped the version in setup.py (0.3.0), because in https://github.com/googlei18n/compreffor/pull/16/commits/d46301596e63cdafe29d2968dc2556183c25a70c I removed `Method.NoPrefs` as a value for the `method` argument of `Compreffor` class.
The reason is the extension module is no longer optional, like it was in the original version of Compreffor, so there's no reason to have a "use the fastest available method" preference any more.
The default is to use the cython extension, and optionally use the pure `Method.Python`.
The `method` arg still take that enum-like object, only that now it can only have values 0 or 1 -- so it might well become just a boolean, IMO.

**Comment by anthrotype** [comment]
Ah, in case you are wondering "how do I run the test suite?", the usual `python setup.py test` should do it.
If you want you can also `pip install tox` and run that locally; by default it will run the test suite on both `python2.7` and `python3.5`. You can pass `-e py27` option to only run on 2.7, for example.

Once this one is merged, I can work on adding support for deploying pre-compiled packages to Github releases (like booleanOperations does), and PyPI too.

**Comment by jamesgk** [comment]
OK to merge? @behdad

**Comment by anthrotype** [comment]
Please hold on. I'm about to push a separate PR with support for building wheels for all the three platforms, including Linux.
I'll break this one into two, the first part enabling running the test suite locally can be merged now; the following with multi-os wheel compilation on CIs is coming soon.

**Comment by anthrotype** [comment]
ok, now this can be merged.

**Comment by anthrotype** [comment]
I changed my mind. Instead of making a new PR, I pushed to this one as the test runner and the CI configuration are interrelated.

I'm using the excellent https://github.com/matthew-brett/multibuild, a set of shell scripts used to build OSX and Linux wheels for the Python scientific stack.
This makes super easy to set up Travis as a Python wheel build farm!

I also configured Travis and Appveyor automatic deployment to Github Releases, but I commented out the section since I don't have push access to the repository, hence I can't generate the auth token.

(If I got push access it would be much easier for you and me ;)

**Comment by anthrotype** [comment]
In case you are thinking, "jeez.. why is this so complicated?", believe me. I did my best to make this simple, but it is quite tricky to build `manylinux1` binary wheels.

**Comment by anthrotype** [comment]
you can follow the progress of the build here:
https://travis-ci.org/anthrotype/compreffor/builds/154319658
https://ci.appveyor.com/project/anthrotype/compreffor/build/1.0.77

**Comment by anthrotype** [comment]
Both the Travis and Appveyor builds pass:
https://travis-ci.org/anthrotype/compreffor/builds/154368358
https://ci.appveyor.com/project/anthrotype/compreffor/build/1.0.79

This can be merged now.

**Pull request merged**
