### PR TITLE
Py23 fixes

### PR DESCRIPTION
**Pull request by adrientetar**
r? @behdad

### CODE REVIEW

**Comment by behdad** [comment]
Thanks!  Are you going to add setup.py logic to compile the extension?

**Comment by anthrotype** [comment]
the thing is it's not a CPython extension module, but a C executable, so it can't be built with distutils. We can add a custom `build_cxx` command to setup.py which uses  `make` via subprocess and builds the executable. Or we can make a real extension module. The first option is easier.

**Comment by behdad** [comment]
Oh, interesting.  Didn't notice that before.  Making real extension sounds best...

That said, the algorithm allows for multi-threaded execution.  Not sure if Sam implemented that.  We want to make sure the Python integration does not inhibit that.

**Comment by adrientetar** [comment]
> Are you going to add setup.py logic to compile the extension?

No.

**Comment by anthrotype** [comment]
I can do that.

**Pull request merged**
